config/routes.rb
CheerupApp::Application.routes.draw do
  

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_for :users do
 get 'users', :to => 'users#show', :as => :user_root # Rails 3
end

  resources :cheerups
  resources :users
  resources :feedbacks, only: [:create, :destroy]
  resources :tweets, only: [:create]

  get '/home', to: 'home#index'
  
  root :to => 'application#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:twitter]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :profile_pic, :location, :username, :tagline, :cover_image_url, :provider, :uid, :oauth_token, :oauth_secret

  has_many :cheerups, :dependent => :destroy
  has_many :feedbacks, :dependent => :destroy

  validates :username, presence: true
  validates_length_of :username, maximum: 12 
  validates :role, :inclusion => {:in => ["admin", "user", "banned", "guest"]}

  mount_uploader :profile_pic, ProfileImageUploader

  after_initialize :defaults

  before_save :update_user_role

  def likes
    self.feedbacks.where(kind: "like")
  end

  def flags
    self.feedbacks.where(kind: "flag")
  end

  def published_cheerups
    self.cheerups.where(state: "published")
  end

  def flagged_cheerups
    self.cheerups.where(state: "flagged")
  end

  def banned_cheerups
    self.cheerups.where(state: "banned")
  end

  def defaults
    self.location ||= 'none'
    self.profile_pic ||= 'none'
    self.tagline ||= 'none'
    self.cover_image_url ||= 'none'
    self.role ||= "guest"
  end

  def self.from_omniauth(auth)
    if user = User.find_by_email(auth.info.nickname+"@twitter.com")
      user.provider = auth.provider
      user.uid = auth.uid
      user.oauth_token = auth.credentials.token
      user.oauth_secret = auth.credentials.secret
      user

    else
      where(auth.slice(:provider, :uid)).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.username = auth.info.nickname
        user.email = auth.info.nickname+"@twitter.com"
        user.password = Devise.friendly_token[0,20]
        user.oauth_token = auth.credentials.token
        user.oauth_secret = auth.credentials.secret
      end
    end
  end


  def role?(role)
    self.role.to_s == role.to_s
  end

  def update_user_role
    if self.role == "guest"
      self.role = "user"
    end
  end

  def rating
    rating = 0

    cheerups.each do |cheerup|
      rating += cheerup.rating
    end
    return rating
  end

  def tweet(cheerup)

    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['CHEERUP_APP_TWITTER_API_KEY']
      config.consumer_secret     = ENV['CHEERUP_APP_TWITTER_API_SECRET']
      config.access_token        = oauth_token
      config.access_token_secret = oauth_secret
    end

    client.update_with_media("Cheerup...", File.new("#{Rails.root}/public"+cheerup.image_url)) 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  
  
  def index
    # @q = Users.search(params[:q])
    # @users = @q.result(distinct: true).order(:created_at).page(params[:page])
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

 
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  
  def edit
    @user = User.find(params[:id])
  end

  
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Your profile was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
        session[:current_user_id] = @user.id

      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
   <div class="field">
    <%= f.label :profile_pic %><br />
    <%= f.file_field :profile_pic %>
  </div>
  <div class="field">
    <%= f.label :cover_image_url %><br />
    <%= f.text_field :cover_image_url %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br />
    <%= f.text_field :tagline %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form2.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
   <div class="field">
    <%= f.label :profile_pic %><br />
    <%= f.file_field :profile_pic %>
  </div>
  <div class="field">
    <%= f.label :cover_image_url %><br />
    <%= f.text_field :cover_image_url %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br />
    <%= f.text_field :tagline %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form2' %>


<%= link_to 'Back', root_path %>

app/views/users/index.html.erb
<h1>All users</h1>

<p>
  Note: Do we even want a index page where to see all users? Perhaps useful for searching users.
<p>


<!-- # <%#= search_form_for @q do |f| %>
#   <p>
#     <%#= f.label :username_cont %>
#     <%#= f.text_field :username_cont %>
#     <%#= f.submit %>
#   </p>
# <%# end %> -->

<ul>
  <% @users.each do |user| %>
    <li>
      Username: <%= link_to user.username, user %>
      Location: <%= user.location %> 
      <%= image_tag user.profile_pic.thumb.url %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>


<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<div id = "cover">
  <%= image_tag @user.cover_image_url %>
</div>

<div id="chicken_wrap">
  <div class = "profile-details">  
    <%= image_tag @user.profile_pic.details.url %>
    <p><%= @user.username %></p>
    <p><%= @user.location %></p>
    <p><%= @user.tagline %></p>
    <% if can? :update, @user %>
    <p><%= link_to 'Edit', edit_user_path(@user) %></p>
    <% end %> 
  </div>
</div>

<div id='cheerups'>
  <h2 id='user'><%= @user.username %>'s Cheerups</h2>
    
  <% @user.published_cheerups.reverse!.each do |cheerup| %>
    <%= link_to cheerup_path(cheerup) do %>
    
    <%= render partial: "/cheerups/cheerup", locals: { type: "thumb", cheerup: cheerup } %>    
    <% end %>
  <% end %>
</div>