config/routes.rb
CheerupApp::Application.routes.draw do
  

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_for :users do
 get 'users', :to => 'users#show', :as => :user_root # Rails 3
end

  resources :cheerups
  resources :users
  resources :feedbacks, only: [:create, :destroy]
  resources :tweets, only: [:create]

  get '/home', to: 'home#index'
  
  root :to => 'application#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @page = params.fetch(:page, 0).to_i
    @amount_of_pages = Cheerup.published.count

    @new_cheerups = Cheerup.published.offset(@page).order(:created_at).reverse_order
    @cheerup = @new_cheerups.first

    @best_cheerups = Cheerup.published
    @best_cheerups.sort!{ |a,b| a.rating <=> b.rating }.reverse!
    @best_cheerups = @best_cheerups[0..1]

    @best_cheerupers = User.all
    @best_cheerupers.sort!{ |a,b| a.rating <=> b.rating }.reverse!
    @best_cheerupers = @best_cheerupers[0..14]

  end

end

app/views/home/_best_cheerupers.html.erb
<h1>Best Cheerupers</h1>

<% @best_cheerupers.each do |user| %>
  <div class="cheeruper">
    <div class="username">
      <%= link_to user.username, user %>
    </div>
    
    <div class="rating">  
      <%= link_to("Rating:", user) %>
      <%= link_to(user.rating, user) %>
    </div> 
  </div>
<% end %>

app/views/home/_best_cheerups.html.erb
<h1>Best Cheerups</h1>

<% @best_cheerups.each do |cheerup| %>
  <%= render partial: "/cheerups/cheerup", locals: { type: "thumb", cheerup: cheerup } %>
<% end %>

app/views/home/_featured_cheerup.html.erb
<div class="cheerup">
  
  <div>
    <%= render partial: "/cheerups/cheerup", locals: { type: "feature", cheerup: @cheerup } %>
  </div>

</div>

app/views/home/_new_cheerups.html.erb
<h1>New Cheerups</h1>

<% @new_cheerups.each do |cheerup| %>
  <%= render cheerup %>
<% end %>

app/views/home/index.html.erb
<main class="home">

<div id="best_cheerups">
  <%= render partial: "best_cheerups" %>
</div>

<div id="featured_cheerup">
  <div class="previous">
  <% if @page-1 >= 0 %>
    <%= link_to home_path(page: @page-1) do %>
      &#9664;
    <% end %>
  <% end %>
  </div>

  <%= render partial: "featured_cheerup" %>

  <div class="next">
  <% if @page+1 <= @new_cheerups.count %>
    <%= link_to home_path(page: @page+1) do %>
      &#9654;
    <% end %>
  <% end %>
</div>

</div>



<div id="best_cheerupers">
    <%= render partial: "best_cheerupers" %>
</div>

</main>