config/routes.rb
CheerupApp::Application.routes.draw do
  

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_for :users do
 get 'users', :to => 'users#show', :as => :user_root # Rails 3
end

  resources :cheerups
  resources :users
  resources :feedbacks, only: [:create, :destroy]
  resources :tweets, only: [:create]

  get '/home', to: 'home#index'
  
  root :to => 'application#index'

end

app/models/cheerup.rb
class Cheerup < ActiveRecord::Base
  attr_accessible :user_id, :image_url, :message, :state, :image_file, :image_data

  belongs_to :user
  has_many :feedbacks

  validates_length_of :message, maximum: 141 
  validates :user_id, presence: true
  validate  :only_one_of_image_url_and_image_file_and_published
  validate :message_and_published
  validate :has_image
  validate :valid_url_for_draft
  validates :state, :inclusion => {:in => ["flagged", "banned", "published", "draft"]}

  scope :bans, -> { where(state: "banned") }
  scope :flags, -> { where(state: "flagged") }
  scope :published, -> { where(state: "published") }
  
  mount_uploader :image_file, CheerupImageUploader

  after_initialize :defaults
  before_validation :image_file_precedence

  include FileUtils
  include Magick

# custom update atttributes: includes make image from data method

  def update_cheerup_attributes(params)
    image_data = params.delete(:image_data)
    if self.update_attributes(params)
      relative_location = "/composite_image_file/#{self.id}/composite_image.png"
      path = "#{Rails.root}/public" + relative_location
      make_dir_if_none_exists(path)
      create_image_from_data(image_data, path)
      self.update_attribute(:image_url, relative_location)
      
    else
      false
    end
  end

  def make_cheerup
    if save
      process_image
      true
    else
      false
    end
  end

  def process_image
    if image_url && image_url != ""
      begin
        new_image = ImageList.new(image_url).resize_to_fit(510, 510)
        relative_location = "/captured_image_file/#{self.id}/image.#{new_image.format.downcase}"
        new_file_location = "#{Rails.root}/public" + relative_location
        make_dir_if_none_exists(new_file_location)
        new_image.write(new_file_location)
        self.image_url = relative_location        
      rescue
        errors.add :base, "unable to access image"

      end

    end
   end

  def make_dir_if_none_exists(file_path)
    dirname = File.dirname(file_path)
    unless File.directory?(dirname)
      FileUtils.mkdir_p(dirname)
    end
  end


  def create_image_from_data(data, path)
    # decode data and remove junk at bigging of base64 file
    image_data = Base64.decode64(data['data:image/png;base64,'.length .. -1])

    File.open(path, 'wb') do |f|
      f.write image_data
    end
  end

  def defaults
    self.state = "draft"
  end

  def likes_count
    self.feedbacks.where(kind: "like").count
  end

  def flags_count
    self.feedbacks.where(kind: "flag").count
  end

  def rating
    rating = 0

    feedbacks.each do |feedback|
      if feedback.kind == "like"
        rating += 1
      elsif feedback.kind == "flag"
        rating -= 1
      end
    end
    return rating
  end

  def calculated_image_url
    if image_url && image_url != "" && image_url.include?("composite_image_file")
      image_url
    elsif image_file.file && image_file != ""
      image_file_url
    elsif image_url && image_url != ""
      image_url
    else
      nil
    end
  end

  private
  def message_and_published
    if self.state != 'draft'
      errors.add :base, "you must include a message to publish a cheerup" if message.nil? 
    end
  end


  def only_one_of_image_url_and_image_file_and_published
    # if self.state != 'draft'
    #   errors.add :base, "you can only include an image or an image url" if image_file_url.present? && image_url.present? 
    # end
  end

  def has_image
    errors.add :base, "Please provide a valid image file." if image_url.blank? && image_file.blank? 
  end

  private
  def valid_url_for_draft
    if state == "draft" && image_url.present?
      errors.add :base, "Url does not appear to be valid." unless URLImageValidator.valid?(image_url)
    end
  end

  private
  def image_file_precedence
    if image_file.file && state == "draft"
      self.image_url = nil
    end
  end
end

app/controllers/cheerups_controller.rb
class CheerupsController < ApplicationController
  
  def index
    @cheerups = Cheerup.published
  end

  def new
    @cheerup = Cheerup.new
  end


  def create
    @cheerup = Cheerup.new(params[:cheerup])
    @cheerup.user = current_user

    valid_for_draft = @cheerup.make_cheerup

    respond_to do |format|
      if valid_for_draft && @cheerup.message
        format.html { redirect_to root_path, notice: 'Cheerup was successfully created.' }
        format.json { render json: @cheerup, status: :created, location: @cheerup }
      elsif valid_for_draft
        format.html { render action: "edit" }
        format.json { render json: @cheerup, status: :image_loaded }
      else
        format.html { render action: "new" }
        format.json { render json: @cheerup.errors, status: :unprocessable_entity }
      end
    end
  end



  def show
    @cheerup = Cheerup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cheerup }
    end
  end

  
 
  def edit
    @cheerup = Cheerup.find(params[:id])
  end

 
  def update
    @cheerup = Cheerup.find(params[:id])
    respond_to do |format|
      if @cheerup.update_cheerup_attributes(params[:cheerup])
        format.html { redirect_to root_path, notice: 'Cheerup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cheerup.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @cheerup = Cheerup.find(params[:id])
    @cheerup.destroy

    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :no_content }
    end
  end










end

app/helpers/cheerups_helper.rb
module CheerupsHelper
end

app/views/cheerups/_cheerup.erb
<div class="cheerup">
    <img src="<%= @cheerup.image_url %>"> 
    <div class="message"><%= @cheerup.message %></div>
</div>

app/views/cheerups/_cheerup.html.haml
/ Takes a local variable: "type" and "cheerup" into its class to determine rendering

= content_for :head do
  = stylesheet_link_tag "cheerups_feature"
  = stylesheet_link_tag "cheerups_thumb"

%section{class: "#{type}" }
  %div.display
    = image_tag(cheerup.calculated_image_url, id: "#{type}_image")
    %div#hearts
      %p{class: "#{type}"}
        = cheerup.rating
      = button_to "", feedbacks_path(cheerup_id: cheerup.id, kind: "like"), class: "heart"
      #tweet_form
        - if current_user && current_user.provider == "twitter"
          = form_for :tweet, url: tweets_path, method: :post do |f|
            = f.hidden_field :cheerup_id, value: cheerup.id
            = f.submit "", class: "tweet_#{type}"
    = button_to "flag if inappropriate", feedbacks_path(cheerup_id: cheerup.id, kind: "flag"), class: "flag"

app/views/cheerups/_cheerup_partial.html.haml
/ Takes a local variable: "type" and "cheerup" into its class to determine rendering

= content_for :head do
  = stylesheet_link_tag "cheerups_feature"
  = stylesheet_link_tag "cheerups_thumb"

%section{class: "#{type}" }
  %div.display
    = image_tag(cheerup.calculated_image_url, id: "#{type}_image")
    %div#hearts
      %p
        = cheerup.rating
      = button_to "", feedbacks_path(cheerup_id: cheerup.id, kind: "like"), class: "heart"
    = button_to "flag if inappropriate", feedbacks_path(cheerup_id: cheerup.id, kind: "flag"), class: "flag"

app/views/cheerups/_form.html.haml
= content_for :head do
  = javascript_include_tag "kinetic-v5.1.0.min.js"
  = javascript_include_tag "cheerups.js", defer: "defer"

- if @cheerup.errors.any?
  %div#error_explanation
    %h2.errors_messages 
      - @cheerup.errors.full_messages.each do |msg|
        = msg

%section#cheerup_modal
  = form_for(@cheerup) do |f|        
    - if @cheerup.calculated_image_url.nil? || @cheerup.id.nil?
      %div.clearfix#image_selector
        %div.field_url
          = f.label "image url"
          = f.text_field :image_url
        %div.field_file
          = f.label "upload image file"
          = f.file_field :image_file

    - if @cheerup.calculated_image_url && @cheerup.id
      %div.field
        = f.label :message
        %br
        = f.text_field :message
        = f.hidden_field :state, value: "published"
        = f.hidden_field :image_data, value: ""
    %div.action
      - if @cheerup.calculated_image_url && @cheerup.id
        = f.submit "Post Cheerup", id: "submit"
      - else
        = f.submit "Update Image", id: "submit"
    %div#canvas{data: @cheerup.calculated_image_url}

app/views/cheerups/edit.html.erb
<%= render 'form' %>


<%= link_to 'Back', root_path %>

app/views/cheerups/index.html.erb
    <%= render @cheerups %>




<p><%= link_to 'Back', root_path %></p>

app/views/cheerups/new.html.haml
= render 'form'

= link_to 'Back', root_path

app/views/cheerups/show.html.erb
<main class="show">

<p>Username:<%= @cheerup.user.username %></p>

<div id="show">
    <%= render partial: "/cheerups/cheerup", locals: { type: "feature", cheerup: @cheerup } %>
</div>

<% if can? :update, @cheerup %>
   
  <p>
    <%= link_to 'Delete Cheerup', @cheerup, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<p><%= link_to 'Back', root_path %></p>

</main>