config/routes.rb
CheerupApp::Application.routes.draw do
  

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_for :users do
 get 'users', :to => 'users#show', :as => :user_root # Rails 3
end

  resources :cheerups
  resources :users
  resources :feedbacks, only: [:create, :destroy]
  resources :tweets, only: [:create]

  get '/home', to: 'home#index'
  
  root :to => 'application#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cheerup</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag    "reset.css" %>
  <%= stylesheet_link_tag    "styles.css" %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>
<header>

  <nav>
    <% if current_user %>
    <div class = "menu-left">
      <ul>
        <li><%= link_to 'Home', root_path %></li>
      </ul>
    </div>
    <div id = "menu-right">
      <ul>
        <li><%= link_to current_user.username, current_user %></li>
        <li><%= link_to image_tag(current_user.profile_pic.thumb.url), current_user, id: "profile_thumb"  %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
    <div id = "menu-center">
      <ul>
        <li><%= image_tag "cheerup_logo2.png", id: "cheerup_logo"  %>
            <%= link_to image_tag("smiley-face.png"), new_cheerup_path %>
        </li>
      </ul>
    </div>
    <% else %>
    <div class = "menu-left">
      <div class='login'>
        <%= link_to "Sign In", new_user_session_path %>
        <%= link_to "Register", new_user_registration_path %>
      </div>
    </div>
    <div id = "menu-center">
      <ul>
        <li><%= image_tag "cheerup_logo2.png", id: "cheerup_logo" %></li>
        <li><%= link_to image_tag("smiley-face.png"), new_cheerup_path %></li>
      </ul>
    </div>
    <% end %>

  </nav>


</header>

<body>

  <% if notice %>
    <div class="notice"><h2><%= notice %></h2></div>
  <% end %>
  <% if alert %>
    <div class="alert"><h2><%= alert %></h2></div>
  <% end %>

  <%= yield %>



<footer>
  <p>Cheerup 2014</p>
</footer>

</body>
</html>